---
name: Make

on:
  schedule:
    - cron: '0 0 1 * *'
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Cargo
        if: runner.os == 'Linux'
        shell: bash
        run: |
          set -xeuo pipefail
          sudo bash -c '
            apt-get update
            apt-get install -y cargo rust{fmt,-clippy}
          ' >/dev/null
          cargo test --quiet
          cargo build --quiet --ignore-rust-version
          cargo clippy --quiet --ignore-rust-version
          cargo fmt --check --all

